### ISSUE TITLE
Message not marked as unread

### ISSUE THREAD

**Issue by thetmkay** [layerhq/Atlas-Messenger-iOS#191] opened 2015-07-02 14:25 UTC
It seems that messages are marked as read if another user sends them a message while they are in the app.

For example:

We are User A. User B is somewhere else who we already have a conversation with which we've read the last message.

1) B sends message while we are in the `ConversationListView`
2) The `lastMessageText` updates but it is marked as read (no blue dot, `is_unread` is `NO`)
3) A exits to another screen. B sends another message. The message is still marked as read, and if A re-enters the `ConversationListView` `lastMessageText` is correctly updated
4) A exits the app from the  `ConversationListView`. B sends a third message. If A re-enters the app in to the  `ConversationListView`, the message is still unread, but `lastMessageText` is updated
5) A exits the  `ConversationListView`, and then exits the app. A re-enters the app (into a different view). A enters  `ConversationListView`, and now the message is marked as unread (yay!).

Is there clear documentation on this behaviour? It seems inconsistent. I believe the intuitive experience is any message not viewed while in the ConversationView should be marked as unread, but this does not seem to be the case.

Thanks!

**Comment by nicholasgreen** [comment] 2015-07-02 15:17
We are having the exact same issue!

**Comment by Spenser** [comment] 2015-12-17 15:41
@thetmkay @nicholasgreen have either of you found a solution to this? I am having the same issue. I downloaded the example app and it also has this issue.

**Comment by chipxsd** [comment] 2015-12-17 19:06
I'm looking into this -- will try to reproduce it.

**Comment by chipxsd** [comment] 2015-12-17 20:55
I'm not sure if I got the use case right. I sent a message from **User B** to **User A** and it seems to get the unread states correctly.

![unread-state-test](https://cloud.githubusercontent.com/assets/1230138/11881739/7409e0f8-a4bd-11e5-9025-c4d247d03aba.gif)

**Comment by Spenser** [comment] 2015-12-18 17:07
![layer tests](https://cloud.githubusercontent.com/assets/6983733/11902433/0ab1f106-a56f-11e5-97f0-872b870b81e2.gif)
Here I sent a message and it was marked unread because I hadn't selected the conversation. Afterwards, I select the conversation and then hit back. Then sent another message to that conversation. It is always marked as read.

**Comment by chipxsd** [comment] 2015-12-21 18:19
Finally got it reproduced:
![atlas-bug- view-controller-probably-still-running](https://cloud.githubusercontent.com/assets/1230138/11937854/c07e3202-a7cb-11e5-807c-de50692a800c.gif)
If you look closely, there's a flicker that happens in the right simulator when we pop the view controller stack (by tapping the `< back` button). It only happens if the input toolbar is the first responder (has keyboard focus).

It's probably a bug in the `ATLMSplitViewController`. Anyway, I got it reproducible, thanks for the report.

**Comment by petec029** [comment] 2016-01-28 03:53
I am running into the same problem and wondering that the solution is to this issue

**Comment by kcoleman731** [comment] 2016-02-04 01:36
@petec029 Can you tell me what version of Atlas + LayerKit you are using? I am attempting to repro and am unable.

**Comment by petec029** [comment] 2016-02-07 19:12
Hi Kevin...since updating to the latest LayerKit and Atlas the problem appears to be resolved.  Thanks responding to my question

**Closed** 2016-02-07 21:48 UTC

**Comment by kcoleman731** [comment] 2016-02-08 17:15
@petec029 Awesome. Thank you for the update.
